import Link from "next/link";
import { Activity, ArchiveRestore, Building2, CheckCircle2, Database, KeyRound, LockKeyhole, ShieldCheck, UserCog } from "lucide-react";

const areas = [
  ["Visão geral", "Confira totais de empresas, empresas ativas, usuários e estado geral da proteção."],
  ["Empresas", "Consulte identificador, quantidade de usuários e situação. Suspenda temporariamente um ambiente ou restaure-o se estiver na lixeira."],
  ["Orçamento", "Ajuste o nome do configurador, o acréscimo para urgência e emergência e o catálogo compartilhado de categorias, serviços e preços."],
  ["Usuários", "Revise pessoa, empresa, perfil, situação e quantidade de módulos liberados. Abra Configurar para ajustar acessos."],
  ["Segurança", "Verifique identidade do proprietário, criptografia, conexão Supabase, limites de requisição, auditoria, recuperação e backups."],
  ["Auditoria", "Revise data, ação, tipo de registro, empresa e identificador do item para investigar alterações e acessos."],
  ["Privacidade", "Acompanhe solicitações dos titulares de dados, assuma o atendimento, conclua com a resposta registrada ou marque a rejeição justificada."],
];

export function ControlManual() {
  return <div className="control-manual">
    <nav className="control-manual-toc" aria-label="Índice do manual"><a href="#acesso">Acesso</a><a href="#mapa">Mapa do painel</a><a href="#empresas">Empresas</a><a href="#usuarios">Usuários e permissões</a><a href="#seguranca">Segurança</a><a href="#auditoria">Auditoria e privacidade</a><a href="#backup">Backup e recuperação</a><a href="#rotina-control">Rotina recomendada</a></nav>
    <section id="acesso" className="control-manual-panel"><small>1 · ENTRADA NO PAINEL</small><h2>Primeiro acesso e login</h2><p>O Fama Control é o painel administrativo do proprietário. Abra o endereço oficial, confira que o domínio está correto e entre com o e-mail autorizado e a senha do proprietário. No primeiro acesso, use <strong>Primeiro acesso do proprietário</strong> para criar a conta autorizada. Se a verificação em duas etapas estiver ativa, informe o código temporário do aplicativo autenticador.</p><div className="control-manual-callout"><KeyRound /><span><strong>Não consegue entrar?</strong> Confirme o e-mail autorizado, confira o código MFA e tente novamente. Não compartilhe senha ou código. Se o problema continuar, use o fluxo de suporte do proprietário.</span></div></section>
    <section id="mapa" className="control-manual-panel"><small>2 · ORIENTAÇÃO DA TELA</small><h2>Mapa visual das áreas</h2><p>O menu lateral leva às áreas principais. Abaixo está um esquema de navegação baseado nos nomes e funções apresentados no painel; a prévia é ilustrativa, sem dados reais.</p><figure className="control-manual-figure"><div className="control-manual-screen-head"><span>Fama Control</span><small>PAINEL DO PROPRIETÁRIO</small></div><div className="control-manual-screen"><nav><b>Visão geral</b><span>Empresas</span><span>Orçamento</span><span>Usuários</span><span>Segurança</span><span>Auditoria</span><span>Privacidade</span></nav><div><strong>Estado da plataforma</strong><div className="control-manual-screen-cards"><i>Empresas cadastradas</i><i>Usuários vinculados</i><i>Segurança</i></div><p>Permissões · Auditoria · Recuperação</p></div></div><figcaption>Esquema ilustrativo do painel. A interface pode variar entre computador e celular.</figcaption></figure><div className="control-manual-area-list">{areas.map(([title, description]) => <article key={title}><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section id="empresas" className="control-manual-panel"><small>3 · AMBIENTES DE CLIENTES</small><h2>Gerenciar empresas e catálogo</h2><ol><li>Em <strong>Empresas</strong>, confirme o nome, o identificador, a quantidade de pessoas e o estado.</li><li>Use <strong>Suspender</strong> para interromper temporariamente o acesso da empresa; use <strong>Reativar</strong> para restaurá-lo.</li><li>O botão <strong>Lixeira</strong> move a empresa para recuperação conforme as regras de retenção; se ela aparecer removida, use <strong>Restaurar</strong>.</li><li>Na área <strong>Orçamento</strong>, altere o nome do configurador, os percentuais de urgência e emergência, categorias, serviços, unidades, preços, margens e os campos solicitados ao montar uma proposta.</li><li>As alterações no catálogo são compartilhadas com o Fama System. Confira preços e campos antes de salvar; só entram em vigor depois de <strong>Salvar alterações</strong>.</li></ol><div className="control-manual-callout"><Building2 /><span>O Fama Control administra cadastro e acesso. As informações operacionais, clientes e valores de cada negócio continuam no espaço da empresa dentro do Fama System.</span></div></section>
    <section id="usuarios" className="control-manual-panel"><small>4 · ACESSO DA EQUIPE</small><h2>Configurar usuários e permissões</h2><ol><li>Localize o usuário pelo nome ou e-mail e confira a empresa, o perfil e a situação do convite.</li><li>Selecione <strong>Configurar</strong> para abrir as permissões individuais.</li><li>Se um modelo estiver disponível, use-o como ponto inicial; depois revise cada módulo marcado.</li><li>Libere apenas o que a pessoa precisa para sua função, e retire o acesso quando deixar de ser necessário.</li><li>Pressione <strong>Salvar acessos</strong> e aguarde a confirmação da gravação no banco.</li></ol><p>O proprietário mantém acesso total. O Fama System aplica as permissões na navegação e nas chamadas ao servidor. Depois de alterar acessos, peça à pessoa para atualizar ou reabrir o sistema.</p><figure className="control-manual-figure"><div className="control-manual-permissions"><UserCog /><div><strong>Permissões por módulo</strong><span><CheckCircle2 /> Clientes e piscinas</span><span><CheckCircle2 /> Agenda e ordens de serviço</span><span>□ Financeiro</span><span>□ Usuários e empresas</span><b className="control-manual-button">Salvar acessos</b></div></div><figcaption>Exemplo visual de seleção por módulo; cada pessoa deve receber somente os módulos necessários.</figcaption></figure></section>
    <section id="seguranca" className="control-manual-panel"><small>5 · PROTEÇÃO E ESTADO</small><h2>Conferir segurança</h2><p>Abra <strong>Segurança</strong> e leia cada indicador, inclusive a data da última conferência. Os cartões informam se a identidade autorizada do proprietário está configurada, se a criptografia está ativa, se o serviço de dados está conectado e se recursos de produção estão disponíveis.</p><div className="control-manual-security"><article><ShieldCheck /><div><h3>Identidade e MFA</h3><p>Use apenas o e-mail do proprietário. Ative MFA e guarde a recuperação do autenticador em local seguro.</p></div></article><article><LockKeyhole /><div><h3>Criptografia</h3><p>Confira se os dados sensíveis estão protegidos. Se houver a ação de proteção de registros existentes, execute-a apenas após revisar o indicador de configuração.</p></div></article><article><Activity /><div><h3>Limites e auditoria</h3><p>Verifique se limites de requisição e eventos de auditoria estão disponíveis.</p></div></article><article><Database /><div><h3>Recuperação</h3><p>Confira o estado de snapshots e backups antes de uma operação de restauração.</p></div></article></div><div className="control-manual-callout"><ShieldCheck /><span>O estado indicado pela tela depende da configuração do ambiente. Se algum item aparecer indisponível, trate isso como uma tarefa de configuração; não presuma que o mecanismo esteja ativo.</span></div></section>
    <section id="auditoria" className="control-manual-panel"><small>6 · RASTREABILIDADE E LGPD</small><h2>Auditoria e solicitações de privacidade</h2><p><strong>Auditoria:</strong> filtre mentalmente por data, evento, entidade, empresa e registro. Use os campos exibidos para entender quando e onde ocorreu uma ação. Os registros de auditoria são informativos; não os apague durante uma investigação.</p><p><strong>Privacidade:</strong> analise o pedido e os detalhes. Use <strong>Assumir</strong> para começar o atendimento. Ao resolver, escolha <strong>Concluir</strong> e registre a resposta final; use <strong>Rejeitar</strong> somente com uma justificativa apropriada. Preserve a confidencialidade e confirme a identidade do solicitante por um canal adequado antes de revelar ou exportar dados.</p></section>
    <section id="backup" className="control-manual-panel"><small>7 · CONTINUIDADE</small><h2>Validar, baixar e recuperar</h2><ol><li>Antes de uma manutenção, abra <strong>Segurança</strong> e selecione <strong>Validar backup</strong>.</li><li>Leia o resultado e confirme se empresas, registros, usuários e anexos esperados foram contados.</li><li>Use <strong>Baixar backup global</strong> somente para armazenar a cópia em local privado, com acesso restrito e retenção definida.</li><li>Para recuperar uma empresa movida para a lixeira, abra a lista Empresas e use <strong>Restaurar</strong>.</li><li>Após a recuperação, verifique o estado, usuários e acesso no Fama System.</li></ol><div className="control-manual-callout"><ArchiveRestore /><span>Não compartilhe backups por link público. Uma cópia de segurança contém informações sensíveis e precisa de proteção equivalente à do sistema.</span></div></section>
    <section id="rotina-control" className="control-manual-panel"><small>8 · ROTINA DO PROPRIETÁRIO</small><h2>Checklist semanal</h2><div className="control-manual-checks"><p><CheckCircle2 /> Revise empresas novas, suspensas e removidas.</p><p><CheckCircle2 /> Confira convites pendentes e permissões de cada pessoa.</p><p><CheckCircle2 /> Confirme MFA, criptografia, auditoria e recuperação.</p><p><CheckCircle2 /> Valide o backup e confira a possibilidade de restauração.</p><p><CheckCircle2 /> Analise eventos recentes e pedidos de privacidade em aberto.</p></div><p className="control-manual-muted">Para operar o CRM, agenda, clientes, serviços ou financeiro, abra o <Link href="https://www.famasystem.online" target="_blank">Fama System</Link>. Este painel é destinado à gestão administrativa da plataforma.</p></section>
  </div>;
}
